#ifndef DEVICE_MIX_DEFINITION_H
#define DEVICE_MIX_DEFINITION_H


#define MAX_DATA_LENGTH 128

typedef enum instrument_max_value
{
    MAX_FLUKE_DIRECT_VOLT = 200,
    MAX_FLUKE_ALTERNATING_VOLT = 200,
    MAX_FLUKE_DIRECT_CURRENT = 2,
    MAX_FLUKE_ALTERNATING_CURRENT = 20,
    MAX_FLUKE_RESISTANCE = 2000,
    MAX_FLUKE_CAPACITANCE = 20000,

    MAX_34401A_DIRECT_VOLT = 2000,
    MAX_34401A_ALTERNATING_VOLT = 2000,
    MAX_34401A_DIRECT_CURRENT = 200,
    MAX_34401A_ALTERNATING_CURRENT = 200,
    MAX_34401A_RESISTANCE = 20000,
} max_value;

typedef enum instrument_check_type
{
    DIRECT_VOLT_TYPE = 0,
    ALTERNATING_VOLT_TYPE,
    DIRECT_CURRENT_TYPE,
    ALTERNATING_CURRENT_TYPE,
    RESISTANCE_TYPE,
    CAPACITANCE_TYPE,
} check_type;

void qt_sleep(int time_msecond);


#endif // DEVICE_MIX_DEFINITION_H
